".oh-my-bash":
  type: archive
  url: "https://github.com/oh-my-bash/oh-my-bash/archive/master.tar.gz"
  stripComponents: 1
  exact: true
  refreshPeriod: "168h"

"{{ joinPath .fontsDir .terminalFont.fileName }}":
  type: file
  url: "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/v3.0.2/patched-fonts/FiraCode/Regular/FiraCodeNerdFontMono-Regular.ttf"
