
".oh-my-bash":
  type: archive
  url: "https://github.com/oh-my-bash/oh-my-bash/archive/master.tar.gz"
  stripComponents: 1
  exact: true
  refreshPeriod: "168h"

"{{ joinPath .fontsDir .terminalFont.fileName }}":
  type: file
  {{ $nerdFontsVersion := includeTemplate "get-github-latest-version" (list "ryanoasis/nerd-fonts" $cache) }}
  url: "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/v{{ $nerdFontsVersion }}/patched-fonts/FiraCode/Regular/FiraCodeNerdFontMono-Regular.ttf"
