#!/usr/local/bin/bash


# if [ -f ~/.bashrc ]; then
#     . ~/.bashrc
# fi

# when I get time sort this out properly you Dick!!

alias gs='git status'
[[ -f ~/.aliases ]] && source ~/.aliases

# scripts for now
export PATH="$PATH:$(du "$HOME/dotfiles/.scripts/" | cut -f2 | tr '\n' ':' | sed 's/:*$//')"

export GOPATH=$HOME/Developer/golang
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

shopt -s checkwinsize

export AWS_VAULT_BACKEND="file"
export HISTSIZE=99999999999999
export HISTFILESIZE=99999999999999
export SHELL_SESSION_HISTORY=0
export EDITOR=nvim
eval "$(rbenv init -)"

rails_migrate_down() {
    version=$(ls db/migrate | fzf | awk -F _ '{print $1}')
    [[ -n "$version" ]] && rails db:migrate:down VERSION="$version"
}

# This is the shit for make to be new
export PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
export GOPATH=/Users/hookercookerman/Developer/golang
export PATH=${GOPATH}/bin:$PATH
export PATH=/Users/hookercookerman/Developer/ethereum/private-network:$PATH
export BOOT_JVM_OPTIONS="-client -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xverify:none"
export PATH=/Users/hookercookerman/.multirust/toolchains/stable/cargo/bin:$PATH


# not sure why
export PATH=/usr/local/opt/node@14/bin/node:$PATH

export PATH="/usr/local/opt/python/libexec/bin:$PATH"

# Path to the bash it configuration
export BASH_IT="/Users/hookercookerman/.bash_it"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='simple'

# (Advanced): Change this to the name of your remote repo if you
# cloned bash-it with a remote other than origin such as `bash-it`.
# export BASH_IT_REMOTE='bash-it'

# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='git@git.domain.com'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/djl/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# (Advanced): Uncomment this to make Bash-it reload itself automatically
# after enabling or disabling aliases, plugins, and completions.
# export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=0

# Load Bash It
source $BASH_IT/bash_it.sh
export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"

export PROMPT_PWD_COLOR="38;5;226"
export GIT_TOKEN=71a49b78e35c36058867814b68955b74303a9311
export CODEFRESH_TOKEN=5d370386129df572945b070e.d213777ef3b262985397956faae23c57

# Use 'skeswa/prompt' which is symlinked to '~/.prompt'.
. ~/.prompt/prompt.bash

# Add git completion to the prompt (comes from 'skeswa/prompt').
. ~/.prompt/git-completion.bash

## neo

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="$HOME/script-overrides/bin:$PATH"

ulimit -n 4096

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
